server:
  port: 8889
logging:
  path: logs
  file: mylog.log
spring:
  application:
    name: myTest
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://30.28.161.217:3306/course
    username: root
    password: root
mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*
